// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skylab.Forms.Infrastructure.Storage;

#nullable disable

namespace Forms.Infrastructure.Migrations
{
    [DbContext(typeof(FormsDbContext))]
    [Migration("20260919194015_AddComponentGroupLifecycle")]
    partial class AddComponentGroupLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.ComponentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnedBy", "ArchivedAt", "CreatedAt");

                    b.ToTable("ComponentGroup", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnonymousResponses")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMultipleResponses")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedFormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiresManualReview")
                        .HasColumnType("boolean");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LinkedFormId");

                    b.ToTable("Forms", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormCollaborator", b =>
                {
                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("FormId", "UserId");

                    b.HasIndex("FormId")
                        .IsUnique()
                        .HasFilter("\"Role\" = 3");

                    b.ToTable("Collaborators", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ArchivedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PendingReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimeSpent")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "IsArchived", "PendingReminderSentAt");

                    b.ToTable("Responses", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMultipleRuns")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowVersionId");

                    b.HasIndex("WorkflowId", "UserId", "Status");

                    b.HasIndex(new[] { "WorkflowId", "UserId" }, "IX_WorkflowInstances_WorkflowId_UserId_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("WorkflowInstances", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStart")
                        .HasColumnType("boolean");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("WorkflowVersionId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowNodes_WorkflowVersionId_Start")
                        .HasFilter("\"IsStart\"");

                    b.HasIndex("WorkflowVersionId", "FormId")
                        .IsUnique();

                    b.HasIndex("WorkflowVersionId", "NodeKey")
                        .IsUnique();

                    b.ToTable("WorkflowNodes", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousStepId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedTransitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PreviousStepId");

                    b.HasIndex("ResponseId")
                        .IsUnique();

                    b.HasIndex("SelectedTransitionId");

                    b.HasIndex("WorkflowInstanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowSteps_WorkflowInstanceId_Open")
                        .HasFilter("\"CompletedAt\" IS NULL");

                    b.HasIndex("WorkflowInstanceId", "Sequence");

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetNodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.HasIndex("WorkflowVersionId", "SourceNodeId", "Trigger", "Priority")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowTransitions_Source_Trigger_Priority");

                    b.ToTable("WorkflowTransitions", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique();

                    b.HasIndex(new[] { "WorkflowId" }, "IX_WorkflowVersions_WorkflowId_Draft")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex(new[] { "WorkflowId" }, "IX_WorkflowVersions_WorkflowId_Published")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("WorkflowVersions", (string)null);
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.Form", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.Form", "LinkedForm")
                        .WithMany()
                        .HasForeignKey("LinkedFormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkedForm");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormCollaborator", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.Form", "Form")
                        .WithMany("Collaborators")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormResponse", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.Form", "Form")
                        .WithMany("Responses")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowInstance", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowVersion", "WorkflowVersion")
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowNode", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.Form", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowVersion", "WorkflowVersion")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowStep", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowStep", "PreviousStep")
                        .WithMany()
                        .HasForeignKey("PreviousStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skylab.Forms.Domain.Entities.FormResponse", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowTransition", "SelectedTransition")
                        .WithMany()
                        .HasForeignKey("SelectedTransitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowInstance", "WorkflowInstance")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("PreviousStep");

                    b.Navigation("Response");

                    b.Navigation("SelectedTransition");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowTransition", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowNode", "SourceNode")
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowNode", "TargetNode")
                        .WithMany()
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflowVersion", "WorkflowVersion")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");

                    b.Navigation("WorkflowVersion");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowVersion", b =>
                {
                    b.HasOne("Skylab.Forms.Domain.Entities.FormWorkflow", "Workflow")
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.Form", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflow", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowInstance", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Skylab.Forms.Domain.Entities.FormWorkflowVersion", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
